name: CMake build release for win

on:
  push:
    branches:
    - release

env:
  BUILD_TYPE: Release

jobs:
  build-release:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'recursive'
        token: ${{ secrets.CONTRIBUTORS_TOKEN }}
    - name: Install Qt
      # Installs the Qt SDK
      uses: jurplel/install-qt-action@v3
      with:
        version: 6.6.2
        host: 'windows'
        target: 'desktop'
        arch: 'win64_msvc2019_64'
        cache: true

    - name: Configure CMake
       # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
       # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
    
    - name: Build
       # Build your program with the given configuration
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} 

    - uses: actions/upload-artifact@v4
      with:
        name: WingCStruct-${{ matrix.os == 'windows-latest' && 'windows' || 'linux' }}-${{ matrix.qt_version }}-build-cache
        path: ${{github.workspace}}/build
    